version: "3"
networks:
  isolated-network:
services:
  mongo:
    image: mongo
    networks:
      - isolated-network
  server:
    depends_on:
      - "mongo"
    networks:
      - isolated-network
  angular-agent:
  angularjs-customer:
